sonar.projectKey=teilorbarcelos_auth-service-go
sonar.projectName=Auth Service Go
sonar.sources=.
sonar.exclusions=**/*_test.go,**/vendor/**,docs/**,scratch/**,tmp/**
sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.go.coverage.reportPaths=coverage.out
